/*
=========================================================
Guests
ゲスト情報・ログイン判定
=========================================================
*/

create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  table_name text,
  seat_number text,
  timeline_url text,
  quiz_url text,
  mission_url text,
  name_kana text,
  group_name text,
  side text,
  seat_label text,
  first_login_at timestamptz,
  login_count integer default 0,
  is_active boolean not null default true
);

create index if not exists guests_name_idx
on public.guests (name);

create index if not exists guests_table_name_idx
on public.guests (table_name);

alter table public.guests
add column if not exists table_name text,
add column if not exists seat_number text,
add column if not exists timeline_url text,
add column if not exists quiz_url text,
add column if not exists mission_url text,
add column if not exists name_kana text,
add column if not exists group_name text,
add column if not exists side text,
add column if not exists seat_label text,
add column if not exists first_login_at timestamptz,
add column if not exists login_count integer default 0,
add column if not exists is_active boolean not null default true;
