/*
=========================================================
Messages
ゲストメッセージ
=========================================================
*/

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  guest_name text not null,
  message text not null,
  guest_id bigint references public.guests(id)
);

create index if not exists messages_created_at_idx
on public.messages (created_at desc);

alter table public.messages
add column if not exists guest_id bigint references public.guests(id);
