/*
=========================================================
Photos
投稿写真のURL管理
=========================================================
*/

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  guest_name text not null,
  image_url text not null,
  file_path text not null,
  caption text,
  is_best_photo boolean default false,
  is_heartwarming_award boolean default false,
  award_title text,
  guest_id bigint references public.guests(id)
);

create index if not exists photos_created_at_idx
on public.photos (created_at desc);

create index if not exists photos_guest_name_idx
on public.photos (guest_name);

alter table public.photos
add column if not exists guest_id bigint references public.guests(id),
add column if not exists is_best_photo boolean default false,
add column if not exists is_heartwarming_award boolean default false,
add column if not exists award_title text;
