/*
=========================================================
Missions
Mission一覧
=========================================================
*/

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  description text,
  category text,
  icon text,
  theme_color text,
  mission_type text,
  points integer default 0,
  is_active boolean default true,
  display_order integer default 0
);

create index if not exists missions_display_order_idx
on public.missions (category asc, display_order asc, created_at asc);

-- =====================================================
-- Add category column
-- =====================================================

alter table public.missions
add column if not exists category text;

alter table public.missions
add column if not exists icon text,
add column if not exists theme_color text;

create unique index if not exists missions_title_idx
on public.missions (title);

insert into public.missions (
  title,
  description,
  mission_type,
  category,
  points,
  is_active,
  display_order
)
values
  (
    '新郎新婦の最高の笑顔を撮ろう',
    '新郎新婦の笑顔がいちばん輝く瞬間を写真に残してください。',
    'photo',
    'Photo Mission',
    10,
    true,
    1
  ),
  (
    '今日一番感動した瞬間を撮ろう',
    '式や披露宴の中で心が動いた場面を写真で投稿してください。',
    'photo',
    'Photo Mission',
    10,
    true,
    2
  ),
  (
    '新郎と写真を撮ろう',
    '新郎との記念写真を投稿してください。',
    'photo',
    'Photo Mission',
    10,
    true,
    3
  ),
  (
    '新婦と写真を撮ろう',
    '新婦との記念写真を投稿してください。',
    'photo',
    'Photo Mission',
    10,
    true,
    4
  ),
  (
    '同じテーブル全員で写真を撮ろう',
    '同じテーブルの皆さんで集まった写真を投稿してください。',
    'photo',
    'Photo Mission',
    10,
    true,
    5
  ),
  (
    '新郎新婦の共通点を5つ見つけよう',
    '二人の似ているところや共通点を5つ考えて回答してください。',
    'text',
    'Story Mission',
    10,
    true,
    6
  ),
  (
    'カラードレスの色を当てよう',
    'お色直しのカラードレスの色を予想して回答してください。',
    'text',
    'Story Mission',
    10,
    true,
    7
  ),
  (
    '新郎・新婦との一番の思い出を書こう',
    '新郎または新婦との思い出を教えてください。',
    'text',
    'Story Mission',
    10,
    true,
    8
  ),
  (
    '未来の二人へアドバイスを書こう',
    'これからの二人へ、応援やアドバイスを送ってください。',
    'text',
    'Story Mission',
    10,
    true,
    9
  ),
  (
    '写真を5枚投稿しよう',
    '写真を5枚以上投稿すると達成です。',
    'challenge',
    'Challenge Mission',
    10,
    true,
    10
  )
on conflict (title) do update
set
  description = excluded.description,
  mission_type = excluded.mission_type,
  category = excluded.category,
  points = excluded.points,
  is_active = excluded.is_active,
  display_order = excluded.display_order;
