/*
=========================================================
Mission Logs
ゲストのMission実行履歴
=========================================================
*/

create table if not exists public.mission_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  guest_id bigint references public.guests(id),
  guest_name text not null,
  mission_id bigint not null references public.missions(id),
  status text not null default 'completed',
  submitted_text text,
  submitted_image_url text,
  is_heartwarming_award boolean default false,
  award_title text
);

create index if not exists mission_logs_guest_name_idx
on public.mission_logs (guest_name);

create index if not exists mission_logs_mission_id_idx
on public.mission_logs (mission_id);

alter table public.mission_logs
add column if not exists is_heartwarming_award boolean default false,
add column if not exists award_title text;
