/*
=========================================================
Seats
席次情報
=========================================================
*/

create table if not exists public.seats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  guest_id bigint references public.guests(id),
  guest_name text not null,
  table_name text not null,
  seat_label text,
  note text
);

create index if not exists seats_guest_name_idx
on public.seats (guest_name);

create index if not exists seats_table_name_idx
on public.seats (table_name);
