/*
=========================================================
Tables
席次表の机配置・位置座標
=========================================================
*/

create table if not exists public.tables (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  table_name text not null,
  display_name text,
  table_number integer,
  x_position integer default 0,
  y_position integer default 0,
  shape text default 'round',
  seat_count integer default 6,
  map_label text,
  area_name text,
  color_theme text,
  is_active boolean not null default true,
  display_order integer default 0,
  note text
);

create index if not exists tables_table_name_idx
on public.tables (table_name);

create index if not exists tables_display_order_idx
on public.tables (display_order asc, table_number asc, id asc);

alter table public.tables
add column if not exists map_label text,
add column if not exists area_name text,
add column if not exists color_theme text,
add column if not exists is_active boolean not null default true,
add column if not exists display_order integer default 0;
