/*
=========================================================
Timeline
当日のタイムスケジュール
=========================================================
*/

create table if not exists public.timeline (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_time text not null,
  title text not null,
  description text,
  location text,
  icon text,
  display_order integer default 0,
  is_active boolean default true
);

create index if not exists timeline_display_order_idx
on public.timeline (display_order asc, id asc);

alter table public.timeline
add column if not exists location text,
add column if not exists icon text;
