/*
=========================================================
Profiles
新郎新婦プロフィール
=========================================================
*/

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  role text,
  name text not null,
  name_kana text,
  nickname text,
  birthday date,
  hometown text,
  hobby text,
  favorite_food text,
  personality text,
  message text,
  display_order integer default 0,
  is_active boolean not null default true
);

create index if not exists profiles_display_order_idx
on public.profiles (display_order asc, id asc);

insert into public.profiles (
  role,
  name,
  name_kana,
  display_order,
  is_active
)
values
  ('新郎', '中川 優', 'なかがわ ゆう', 1, true),
  ('新婦', '田所 彩加', 'たどころ あやか', 2, true)
on conflict do nothing;
